FROM maven:3-jdk-8-slim

# skip installing gem documentation

RUN cd $HOME && curl https://alumnouaemex-my.sharepoint.com/:u:/g/personal/eacevedod_uaemex_mx/EcDBaQdj3QVIu8LAPHPMtikBcYaZCTlylC3YK8Vo49JcCQ?e=6HHFax
RUN CD $HOME && tar zxvf .m2.tar.gz

EXPOSE 8080
